### ISSUE TITLE
Por quê o nome 7c0?

### ISSUE THREAD

**Issue by vitor-mafra** [projeto7c0/faq#1]
O título do projeto não me parece ter sido explicado (ao menos não consegui achar nada do tipo). Sempre que quero buscar pelo perfil no Twitter acabo tentando todas as combinações entre "7", "c" e "0" hahaha por isso queria entender melhor o porquê do nome - o que pode ser uma coisa útil pra outras pessoas também, acho que vale uma sugestão pra deixar essa informação mais clara

**Comment by lagolucas** [comment]
Sempre me recusarei a explicar a origem do nome 7c0.

E realmente não acho que saber o motivo da escolha vai ajudar a lembrar a ordem 7c0...
